[package]
name = "newsletters"
version = "0.1.0"
authors = ["silvia"]

[dependencies]
iron = "0.5.1"
router = "0.5.1"
postgres = "0.14.1"
serde = "1.0.6"
serde_json = "1.0.1"
serde_derive = "1.0.6"
log = "0.3.7"
env_logger = "0.4.2"
hyper = "0.10.9"
hyper-native-tls = "0.2.2"